spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: Study-config-mr-dev
---
spring:
  profiles: test #测试环境
  application:
    name: Study-config-mr-test
#保存为UTF-8